### ISSUE TITLE
Handling non standard differences between get and fetch urls

### ISSUE THREAD

**Issue by slightlytyler** [mgcrea/redux-rest-resource#1]
So if I create a resource
```javascript
export const {types, actions, reducers} = createResource({
  name: 'user',
  url: `${hostUrl}/users/:id`
});
```
I can expect the the `get` action to make a request to `http://.../users/:id` and the `fetch` action to make a request to `http://.../users`. (Correct me if I'm wrong)

How would you handle a `get` request to `http://.../users/:id` and a `fetch` request to `http://.../users/find/owner`. API can't be changed, it's not mine. If it's not currently possible I'll gladly PR if we can agree on API. Definitely interested in giving this lib a whirl in my current project!

**Comment by mgcrea** [comment]
I think an API like this could do the job to override urls for any action:

```js
export const {types, actions, reducers} = createResource({
  name: 'user',
  url: `${hostUrl}/users/:id`,
  actions: {
    fetch: {
      url: `${hostUrl}/users/find/owner`
    }
  }
});
```
