### ISSUE TITLE
Ability to Customize Store and Parse Custom Headers: Content-Range

### ISSUE THREAD

**Issue by tobrien** [mgcrea/redux-rest-resource#14]
I use redux-rest-resource in combination with epilogue which makes use of the Content-Range header to specify the range of records returned.  For this to be useful to me I need to parse this header and make it available.

I've implemented this over here - https://github.com/tobrien/redux-rest-resource/commit/661092d692f0afa576558ab9af6d6b58390e67e6

But, it feels like a hack.  Ideally one would be able to specify some additional properties and some callbacks when creating the resource, but the default transformer is pretty harsh (it doesn't incude any headers.)

Anyway, just throwing this out here in case anyone is interested or has a similar need.

**Comment by mgcrea** [comment]
A bit late, but you do have access to the response headers while in the tranform pipeline.

Just use `res.headers.get('Content-Type');`

I guess one remaining issue would be the handling of custom keys in the state.

**Comment by mgcrea** [comment]
Would the #24 option fit your needs?
