### ISSUE TITLE
headers override in actions is not working

### ISSUE THREAD

**Issue by adevofficial** [mgcrea/redux-rest-resource#27]
When i try to provide headers here its not passed to the fetch
actions.updateUser({firstName: 'Olivier'}, {headers: {Authorization: `Bearer ${jwt}`}});

**Comment by mgcrea** [comment]
Should be working fine now as it is covered by [this test](https://github.com/mgcrea/redux-rest-resource/blob/master/test/spec/actions.spec.js#L1675)
