### ISSUE TITLE
handling HttpErrors, NotFound, change of Item/s

### ISSUE THREAD

**Issue by mugwump** [mgcrea/redux-rest-resource#34]
Hopefully I'm only having issues to understand how to handle redux-rest-resource: The basic use-cases work like a charm and have reduced a lot of boilerplate-code we had in our redux.

But now we have a very simple use-case where I'm having issues to handle it properly:

we have a text-field to enter an id, this id should then be checked if it exists (using a get<Resource>) and return an item. The result can either be an item (if the id exists), or a http 404 if it doesn't. 

- How do I handle the 404? it seems like http-errors just fall through and don't change the redux-state?! Or is this configurable and I have not yet found the right way to do it? What happens with other http-errors (e.g a 403) - how can I intercept these and handle them properly?
- When my first search returned an item, and I search for another item that does not exist, how do I determine that redux-fetch-resource has done the search and did no find anything? Under the redux-key <Resource>.item the item does not change, the only thing changing is the isFetching-key: Unless I somehow store the state locally (which is something I'm trying to avoid), there is no way to determine that the last query and the result in .item do not fit together. Or is there?!

I'm probably misunderstanding r-r-r, but I could not find anything in the docs/examples to handle these use-cases... - so thx for any help/hint!

**Comment by mugwump** [comment]
ok, the actions are already being dispatched: We get an action `@@resource/<RESOURCE NAME>/GET` with a status of `rejected ` - so instead of registering the resource-reducer directly, we can register a error reducer, that registers for the `@@resource/<RESOURCE NAME>/GET`-actions with status `rejected`.

for this to work we have moved the original reducer to the key `request` and added our error-reducer under `error`:

`const { types, actions, rootReducer } = resource;
const resoureReducer = combineReducers({
  request: rootReducer,
  errors: errorReducer
});`

Now the request/errors combination always tells the story about how a request went through. 

Although this works, I am not sure, if this is the right approach: 

- shouldn't this kind of explicit error-handling be part of r-r-r?
- although the http-exception are caught by rrr to dispatch the error-action, the exception is re-thrown and ends up uncaught in the console. While this may be appropriate for actual errors like a 500, I would like to catch a 404, as this is how our reports that a label for this id does not exist, so it is not a server-error. 

Anyway, it works now, but I would really appreciate if someone with a little more experience with rrr would comment on this solution - I hopefully just have missed something here, as it should be easier he solution I found...

**Comment by mgcrea** [comment]
Having a custom reducer is indeed the goto way to handle errors via a redux state currently. Another option is to catch actions Promise rejections (ignoring the state).

Agree r-r-r could do more to smooth a little bit the experience here, but I was not really fond of bloating the state with error-related props (would need at least one for every action, eg. `hadFetchingError: {code: Number, body: Object} | null`). What do you think?

Regarding not throwing back certain errors, we could use an option for that, but it's needed for out-of-store error handling by catching promises.

**Comment by izaleu** [comment]
I have a similar question to OP. My use case is that I'm trying to record all rejected Promises and send them to a logging service. Is there a way I can do that without writing a custom reducer for every single resource?

**Comment by mgcrea** [comment]
@izaleu catching promises meant wrapping any action with a `.catch()`, eg. `actions.fetchUsers().catch(myErrorHandler).

I've recently added an option to handle such cases more gracefully with a `beforeError` hook:

You can see the code here: https://github.com/mgcrea/redux-rest-resource/commit/b01f41b0550af3a9aa70796102074de3efd2dacb

Example:

```js
const {actions, reducers: resouceReducers} = createResource({
  name: 'enrollment',
  url: `${HOST_API_URL}/worker/enrollments/:_sid`,
  credentials: 'include',
  actions: {
    abort: {method: 'POST', gerundName: 'aborting', url: './abort'},
    archive: {method: 'POST', gerundName: 'archiving', url: './archive'}
  },
  beforeError: [handleHttpError]
});
```

```
export const handleHttpError = err => {
  const {status = 500} = err;
  console.warn(`XHR request failed with status=${status}`, err);
  if (status === 401) {
    navigate('SignIn', {});
    return;
  }
};
```

**Comment by josias-r** [comment]
Pleeeease add this to the documentation 🙏🏻
