### ISSUE TITLE
Setting `isArray: false` on a fetch action does not alter response handling

### ISSUE THREAD

**Issue by alkamin** [mgcrea/redux-rest-resource#36]
I'm creating a resource like so:

```
export const {
  types: projectTypes,
  actions: projectActions,
  rootReducer: projectReducer
} = createResource({
  name: "projects",
  url: `${config.api}/projects/:id`,
  headers: getState => ({ Authorization: `Bearer ${getState().auth.idToken}` }),
  actions: {
    fetch: {
      method: "GET",
      isArray: false
    }
  }
});
```

The API we're interacting with returns paginated responses, which have a general shape of:

```
{
    count: 59
    hasPrevious: false
    hasNext: true
    page: 0
    pageSize: 30,
    results: [{...}, {...}, ...]
}
```
1) Thanks for the useful library!

2) My expectation was that setting `isArray` would result in the response being stored in the `item` property of the state as an object rather than being set as the first element in an array within the `items` property. It's making for some awkward lookups.

3) I'm assuming that the best way to work-around this for the time being would be to implement a custom reducer?

**Comment by kde3kko** [comment]
(Probably too late...)
I think one viable approach would be using a transformResponse to extract your ```results``` into the state ```items```.
Have a look here:

https://mgcrea.gitbook.io/redux-rest-resource/advanced/transform-response
