### ISSUE TITLE
delete action clears the entire state

### ISSUE THREAD

**Issue by tomsoderlund** [mgcrea/redux-rest-resource#38]
Hi, thanks for a great lib!

Seems like `delete` action clears the entire state – does it expect the REST endpoint to return _all_ the items?

Tried to implement a custom reducer with:

    actions: {
      delete: { reduce: (state, action) => {
        console.log('My custom reducer')
        return state
      } }
    }

...but doesn't seem to be triggered, any hints?

Thanks!

**Comment by mgcrea** [comment]
A `delete` action on the entire collection will clear the state (eg `DELETE /api/users`), as it is expected to actually clear the collection. A `delete` on a single id (eg `DELETE /api/users/userId`) should not clear the state.

There is support for a `idKeyMulti` to support collection DELETE only for specific items, see https://github.com/mgcrea/redux-rest-resource/blob/master/src/reducers/index.js#L263

In that case you usually have to add `{ids: [A, B, C]}` in your body, should also work inside queryParams.
