### ISSUE TITLE
remove 'content-type: application/json' in header in GET request

### ISSUE THREAD

**Issue by jacktang** [mgcrea/redux-rest-resource#39]
Hello,

I think it is not necessary to put `content-type:application/json` in header when send `GET` request using `fetch`. When the requesting is cross-domain, it will produce `OPTIONS` preflight request. How about to remove the header in `GET` request?

**Comment by jacktang** [comment]
Well, i write axios adapter to solve the problem.

**Comment by brettjonesdev** [comment]
@jacktang have you published that axios adapter anywhere, or mind sharing a `gist` of what your code looks like? I'm thinking of using this library but all our clients use `axios` so I'd love to get a head start on an adapter if you don't mind sharing!

**Comment by jacktang** [comment]
@brettjonesdev my axios adapter list below:

```
import axios from 'axios';

const axiosFetch = (url, options = {}) => {
  let axiosOpt = Object.assign({}, { 'url': url }, options);
  if (axiosOpt.method !== 'GET') {
    axiosOpt.data = axiosOpt.body;
  }
  return axios(axiosOpt)
    .then(res => {
      if (!res) return
      res.headers.get = (key) => {
        return res.headers[key.toLowerCase()];
      };
      res.json = () => {
        return new Promise((resolve, reject) => {
          resolve(res.data);
        });
      };
      res.ok = true;
      return res;
    });
};

export default axiosFetch;
```

**Comment by brettjonesdev** [comment]
Awesome, thanks @jacktang!
