### ISSUE TITLE
GET items

### ISSUE THREAD

**Issue by yoongfook** [mgcrea/redux-rest-resource#4]
First of all thank you so much for this library - i initially made my own class but yours is so much better!

In your example, you mapped the users state to props, then then loop through it to render the each of them. 

However in the reducer, the resulting collection from the GET request is actually within resource > items.

![redux_devtools](https://cloud.githubusercontent.com/assets/1704381/18811801/473b1524-8301-11e6-9c1e-5213fae7f324.jpg)

Am i doing something wrong ?

**Comment by mgcrea** [comment]
The readme was indeed outdated, thanks for using the lib!
