### ISSUE TITLE
Chaining async actions

### ISSUE THREAD

**Issue by dodlesApp** [mgcrea/redux-rest-resource#43]
Is there an easy way of chaining another action to one of the REST actions?

In my use case I have two stores for two different but related resource types. When a resource of type A is created successfully, I need to trigger a resource of Type B to be created.

**Comment by mgcrea** [comment]
I think you probably should just manually export (or define) a new action that combines them and use that instead.

eg.

```js
actions.myConbinedAction = async (...) => {
  const a = await actions.fetchUsers(...);
  const b = await actions.updateUser(...);
  return [a, b];
}
```
