### ISSUE TITLE
Update items for custom actions

### ISSUE THREAD

**Issue by chirhotec** [mgcrea/redux-rest-resource#44]
I created a custom action to call an RPC endpoint on my server, which returns an updated version of the object. However, when the response comes back, it does not update the corresponding object in the redux store. Even if I set `assignResponse: true` it doesn't work.

**Comment by mgcrea** [comment]
[`assignResponse`](https://mgcrea.gitbook.io/redux-rest-resource/advanced/assign-update-response) only works for the existing update action.

You should be able to use the `reduce` option to pass a custom reducer:

```js
reduce: (state, action) => ({...state, foo: 'bar'})
```

**Comment by chirhotec** [comment]
perfect, thanks!
