### ISSUE TITLE
Can u provide some example with additional actions with custom transform ?

### ISSUE THREAD

**Issue by zhDmitry** [mgcrea/redux-rest-resource#6]
It will be cool if you provide some example with custom actions creator. ( with immutablejs or normalizr will be preffered )

**Comment by yoongfook** [comment]
@kraken97 did you find out how to do this? are you trying to add some custom actions to the usual ones?

**Comment by mgcrea** [comment]
I haven't played with either immutablejs or normalizr yet. But custom actions are properly handled now: see http://mgcrea.github.io/redux-rest-resource/docs/advanced/CustomActions.html
